base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
quant:
    method: RTN
    weight:
        bit: 8
        symmetric: False
        granularity: per_group
        group_size: 128
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_fp: False
    save_quant: True
    save_path: ./save_w8a8