base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
eval:
    eval_pos: [pretrain, fake_quant]
    name: [wikitext2, c4, ptb]
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: RTN
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
save:
    save_fp: False
    save_quant: False
    save_path: ./save