base:
    seed: &seed 42
model:
    type: Llama
    path: model path
    torch_dtype: auto
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: HQQ
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 128
        round_zp: False
    special:
        axis : 0
        lp_norm : 0.7
        beta : 10
        kappa : 1.01
        iters : 20
save:
    save_fp: False
    save_quant: False
    save_path: ./save