base:
    seed: &seed 0
model:
    type: Llama
    path: model path
    torch_dtype: auto
calib:
    name: c4
    download: False
    n_samples: 128
    path: calib data path
    bs: 1
    seq_len: 2048
    preproc: c4_gptq
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    bs: 1
    seq_len: 2048
quant:
    method: SpQR
    weight:
        bit: 4
        symmetric: False
        granularity: per_group
        group_size: 16
        round_zp: False
    special:
        actorder: True
        percdamp: 1
        blocksize: 128
        true_sequential: True
        relative_threshold: 0.2
        simplified_outliers: False
        scale:
            bit: 3
            symmetric: False
            granularity: per_group
            group_size: 16
            round_zp: False
        zero:
            bit: 3
            symmetric: False
            granularity: per_group
            group_size: 16
            round_zp: False
    quant_out: True
save:
    save_fp: False
    save_quant: False
    save_fake: False
    save_path: ./save
